[package]
name = "emplace"
version = "0.1.4"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
description = "Command-line tool to mirror installed software on multiple machines."
edition = "2018"
repository = "https://github.com/tversteeg/emplace"
readme = "README.md"
license = "AGPL-3.0-or-later"
keywords = ["shell", "cli", "mirror"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[badges]
is-it-maintained-issue-resolution = { repository = "tversteeg/emplace" }
is-it-maintained-open-issues = { repository = "tversteeg/emplace" }

[dependencies]
ansi_term = "0.12.1"
clap = "2.33.0"
dialoguer = "0.4.0"
dirs = "2.0.2"
git2 = "0.10.1"
indicatif = "0.12.0"
lazy_static = "1.4.0"
regex = "1.3.1"
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.40"
toml = "0.5.3"
