name: emplace
version: git
summary: Synchronize installed packages on multiple machines
description: |
  emplace is a command line tool for synchronizing,
  mirroring and installing packages installed using
  a package manager between multiple machines.
confinement: devmode
base: core18
parts:
  emplace:
    plugin: rust
    source: .

apps:
  emplace:
    command: bin/emplace
